volumes:
  static:
  logs:
  gallery-data:

services:
  web:
    build:
      context: ./django
    container_name: ig-web
    ports:
      - "8000:8000"
    volumes:
      - static:/opt/static/
      - logs:/opt/logs/
      - ./django:/opt/
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres:16.2
    container_name: ig-db
    volumes:
      - gallery-data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432

  proxy:
    platform: linux/amd64
    image: nginx:latest
    container_name: ig-proxy
    depends_on:
        - web
    ports:
        - "80:80"
    volumes:
        - ./nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
    env_file: .env

