version: '3.8'

volumes:
  gallery-data:

services:
  web:
    build: ./gallery-web
    container_name: ig-web
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file: .env

  api:
    build:
      context: ./fastapi
    container_name: ig-api
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi/config.json:/usr/src/app/config.json
      - ./fastapi/gcp-service-account.json:/usr/src/app/gcp-service-account.json
      - ./fastapi/:/usr/src/app/
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres:16.2
    container_name: ig-db
    volumes:
      - gallery-data:/var/lib/postgresql/data
    env_file: .env

  proxy:
    platform: linux/amd64
    image: nginx:latest
    container_name: ig-proxy
    depends_on:
        - web
    ports:
        - "80:80"
    volumes:
        - ./nginx/templates/:/etc/nginx/templates/
    env_file: .env

